# Problem 33: Write a function nearly_equal to test whether two strings are nearly equal. Two strings a and b are nearly equal when a can be generated by a single mutation on b.

# import mutate


# def nearly_equal(a,b):
# 	return a in mutate.mutate(b)

# if __name__ == '__main__':
# 	print(nearly_equal('helo','hello'))
# 	print(nearly_equal('hello','hel'))
